export const FORUM_REQUEST = "FORUM_REQUEST";
export const FORUM_FAILURE = "FORUM_FAILURE";
export const GET_FORUM_SUCCESS = "GET_FORUM_SUCCESS";
export const POST_FORUM_SUCCESS = "POST_FORUM_SUCCESS";
export const PATCH_FORUM_SUCCESS = "PATCH_FORUM_SUCCESS";
export const DELETE_FORUM_SUCCESS = "DELETE_FORUM_SUCCESS";
